# -*- coding: utf-8 -*-
"""Location_ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17_H6xr7ugxrplrco9vqCn6s-Q5JxTMls

Load Dataset
"""

import pandas as pd
from pandas import read_csv 
from sklearn.model_selection import train_test_split
from sklearn import svm
import numpy as np
import pickle



fileName = "location.csv"
dataset = pd.read_csv(fileName)

"""Load & summarize dataset"""

#print(dataset.shape)
#print(dataset.tail(5))

#print(dataset.describe())

"""Segreggating dataset into X(input/independentVariable) & Y(output/dependentVariable)

Splitting Dataset to Train & Test
"""

array = dataset.values
X = array[:,0:7]
Y = array[:,7]
X_train, X_validation, Y_train, Y_validation = train_test_split(X ,Y, test_size = 0.20, random_state = 1)

"""Algorithm"""

model = svm.SVC(gamma='auto')

model.fit(X_train, Y_train)

result = model.score(X_validation, Y_validation)
#print(result)

"""-
+Prediction
"""

value = [[23,62,85,18.97424756,19.5161216,8.490127142,80.7108745]]
predictions = model.predict(value)
final_prediction=predictions[0]
print(final_prediction)

"""Accuracy"""

from sklearn.metrics import accuracy_score
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

#print('Accuracy on Training data : ', training_data_accuracy)

file ='location_code.pkl'
fileobj = open(file,'wb')
pickle.dump(model,fileobj)


model = pickle.load(open(file,'rb'))
pred = model.predict(value)
print(pred)
